# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.2.0"

gem "sinatra", "~> 4.1"
gem "puma", "~> 6.5"
gem "google-apis-sheets_v4", "~> 0.38"
gem "googleauth", "~> 1.11"
gem "dotenv", "~> 3.1"
gem "rack-cors", "~> 2.0"

group :test, :development do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.1"
  gem "mocha", "~> 2.7"
end
